"""add deleted_at to task

Revision ID: 6f058802bd48
Revises: 1c96c9d92ecb
Create Date: 2026-01-17 17:22:40.190579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f058802bd48'
down_revision = '1c96c9d92ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deleted_at')
    # ### end Alembic commands ###
